### ISSUE TITLE
Loop until button doesn't exist

### ISSUE THREAD

**Issue by jboivin-done** [bahmutov/cypress-recurse#276]
I am using this plugin to bypass a tutorial if it is present.

```
cy.recurse(
    () => cy.get('.MY-BUTTON-CLASS').if().click(),
    (nextButton) => nextButton === null,
    {timeout: 100000}
);
```

I don't know in advance how many steps there are in the tutorial. Thus, I don't how long it would take to skip the whole tutorial. I currently set an high enough `timeout`, but I think the real solution would be:
- No timeout
- Reseting the timeout on each loop

Do you have any suggestions to remove this arbitrary timeout value?

**Comment by bahmutov** [comment]
I don't think removing the timeout makes sense. You might just increase it and use the limit parameter, but if there is a tutorial that has 1000 steps, that would be unexpected and I would assume the test should catch it.

**Comment by jboivin-done** [comment]
Well, I had to add the limit parameter too as I realized it could crash due to that too.

I admit, a tutorial with 1000 steps or more should not exist, but my point here is: arbitrary timeout and limit values. I don't like arbitrary values because let's say I first put there 100. This would be more easy to reach this limit. Using a `if` in conjunction with `recurse`, there is no need for a timeout. Don't you think?

How would you do it without having arbitrary values?

**Comment by bahmutov** [comment]
I would put sanity limits. There should be less than 10 steps and it should take less than 5 seconds for example Sent from my iPhoneOn Mar 26, 2024, at 14:22, jboivin-done ***@***.***> wrote:﻿
Well, I had to add the limit parameter too as I realized it could crash due to that too.
I admit, a tutorial with 1000 steps or more should not exist, but my point here is: arbitrary timeout and limit values. I don't like arbitrary values because let's say I first put there 100. This would be more easy to reach this limit. Using a if in conjunction with recurse, there is no need for a timeout. Don't you think?
How would you do it without having arbitrary values?

**Comment by jboivin-done** [comment]
I agree. I will use that for now.

BTW, it would be sharp to have an example like this one somewhere in the doc.

Thank you for your quick response.

**Comment by bahmutov** [comment]
If I create an example like this one, it will probably go into my course "Cypress Plugins" https://cypress.tips/courses/cypress-plugins
